### ISSUE TITLE
Use repository to house source

### ISSUE THREAD

**Issue by yoiang** [subtledoctor/OS-X-Weidu-Launcher#2]
Hey @subtledoctor ! I appreciate the launcher, it'd be great to help with it's development and contribute features. Do you have any plans to use the git repo to track and share the source?

**Comment by subtledoctor** [comment]
Okay, I just noticed this and it's five years old so I assume it is moot. Gonna close this issue. But, FWIW, the source is hosted here. I don't think Github can display the Applescript at the heart of this, but if you right-click the app to "show contents" and then navigate to "/content/resources/scripts" then you can find the .scpt file and open is with Apple's Script Editor.
